<a href="https://colab.research.google.com/github/Hardik-India/Machine_Learning/blob/main/Mini_Batch_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_diabetes

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import r2_score

In [ ]:
x,y = load_diabetes(return_X_y=True)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)
reg = LinearRegression()
reg.fit(x_train,y_train)
y_pred = reg.predict(x_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [ ]:
print("Betas value : ",reg.coef_)
print("Intercept value : ",reg.intercept_)

Betas value :  [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
Intercept value :  151.88331005254167


In [ ]:
import random
class MBGDRegressor:

  def __init__(self,batch_size,learning_rate,epochs):
    self.coef_ = None
    self.intercept_ = None
    self.lr = learning_rate
    self.epochs = epochs
    self.batch_size = batch_size

  def fit(self,x_train,y_train):
    # initialize the coef with all ones and the intercept with 0
    self.intercept_ = 0
    self.coef_ = np.ones(x_train.shape[1])

    for i in range(self.epochs):
      for j in range(int(x_train.shape[0]/self.batch_size)):

        # Generating Random numbers based on batch size
        idx = random.sample(range(x_train.shape[0]),self.batch_size)

        y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_

        # calculating the intercept values
        intercept_der = -2 * np.mean(y_train[idx] - y_hat)
        self.intercept_ = self.intercept_ - (self.lr * intercept_der)

        # calculating the coefficient values
        coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
        self.coef_ = self.coef_ - (self.lr * coef_der)

  def predict(self,x_test):
    return np.dot(x_test,self.coef_) + self.intercept_

In [ ]:
mbr = MBGDRegressor(batch_size=int(x_train.shape[0]/10),learning_rate=0.01,epochs=500)

In [ ]:
mbr.fit(x_train,y_train)

In [ ]:
mbr.coef_

array([  -4.27480206, -204.55876065,  522.87544552,  339.15748536,
        -76.37943503, -103.22006983, -185.15733656,   82.53986579,
        543.8028545 ,   47.3494132 ])

In [ ]:
mbr.intercept_

np.float64(144.77988310938986)

In [ ]:
y_pred = mbr.predict(x_test)

In [ ]:
r2_score(y_test,y_pred)

0.4333258869168487

In [ ]:
import random
random.sample(range(x_train.shape[0]),10)

[7, 107, 79, 8, 82, 196, 326, 55, 270, 287]

# MBGD using sklearn class (SGD Regressor)

In [70]:
from sklearn.linear_model import SGDRegressor

In [71]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [81]:
batch_size = 35

for i in range(100):
  idx = random.sample(range(x_train.shape[0]),batch_size)
  sgd.partial_fit(x_train[idx],y_train[idx]) #Loads only one chunk of data

In [82]:
sgd.coef_

array([   9.95877889, -166.27443989,  493.00964527,  310.05897051,
        -35.7744775 , -101.15738573, -202.05072697,  115.65898344,
        442.3500068 ,   78.30634605])

In [83]:
sgd.intercept_

array([152.22639155])

In [84]:
y_pred = sgd.predict(x_test)
r2_score(y_test,y_pred)

0.4562495291879777