<a href="https://colab.research.google.com/github/Hardik-India/Machine_Learning/blob/main/Stochastic_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
from sklearn.datasets import load_diabetes

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import r2_score

In [18]:
x,y = load_diabetes(return_X_y=True)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)
reg = LinearRegression()
reg.fit(x_train,y_train)
y_pred = reg.predict(x_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [19]:
print("Betas value : ",reg.coef_)
print("Intercept value : ",reg.intercept_)

Betas value :  [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
Intercept value :  151.88331005254167


In [30]:
class SGDRegressor:

  def __init__(self,learning_rate,epochs):
    self.coef_ = None
    self.intercept_ = None
    self.lr = learning_rate
    self.epochs = epochs

  def fit(self,x_train,y_train):
    # initialize the coef with all ones and the intercept with 0
    self.intercept_ = 0
    self.coef_ = np.ones(x_train.shape[1])

    for i in range(self.epochs):
      for j in range(x_train.shape[0]):
        idx = np.random.randint(0,x_train.shape[0])

        y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_

        intercept_der = -2 * (y_train[idx] - y_hat)
        self.intercept_ = self.intercept_ - (self.lr * intercept_der)

        coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
        self.coef_ = self.coef_ - (self.lr * coef_der)

  def predict(self,x_test):
    return np.dot(x_test,self.coef_) + self.intercept_

In [87]:
sgd = SGDRegressor(learning_rate=0.2,epochs=60)

In [88]:
sgd.fit(x_train,y_train)

In [89]:
sgd.coef_

array([ -66.22130036, -205.07718336,  526.07612712,  325.25017797,
       -146.61528595,  -33.53902651, -159.20773769,   53.94345927,
        555.982555  ,   79.74350527])

In [90]:
sgd.intercept_

np.float64(158.63331077728026)

In [91]:
y_pred = sgd.predict(x_test)
r2_score(y_test,y_pred)

0.44408116895153793

In [92]:
from sklearn.linear_model import SGDRegressor
sg = SGDRegressor(learning_rate='constant',eta0=0.1)
sg.fit(x_train,y_train)
sg.coef_

array([  21.66949949, -152.51067116,  462.26739623,  310.62324792,
        -29.36933613, -101.75196649, -193.60041779,  109.29041235,
        425.22989983,  106.0935422 ])

In [93]:
sg.intercept_

array([161.50866256])